apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: home
  namespace: home
spec:
  template:
    metadata:
      name: <NEW NAME>
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: <NEW IMAGE>
          ports:
            - containerPort: 80
